### ISSUE TITLE
Supportnfor mqtt v5?

### ISSUE THREAD

**Issue by yombo** [astrorafael/twisted-mqtt#12]
First, thanks for this package!

Any thoughts of updating it to support mqtt v5?

**Comment by astrorafael** [comment]
Hi,

Unfortunatley not. 

This package was born by my need to have a working twisted MQTT library for my project, which even as of today, it doesn't exists in the Twisted project, so I had to roll my own. 

I wish people from TwistedMatrix could have evolved it and incoporated into its core. 

For my project, v3.1 is enough and  it is working fine and I'm quite happy with it. I don't really have the time or need to upgrade to mqtt v5.
