### ISSUE TITLE
Is ssl connection working?

### ISSUE THREAD

**Issue by wexi** [astrorafael/twisted-mqtt#13]
Hi,

twisted-mqtt works well for me with 
'tcp:host=test.mosquitto.org:port=1883' **but not** with 'ssl:host=test.mosquitto.org:port=8883:caCertsDir=/etc/ssl/certs'
and there is no error message.

Has it been tested? I'm using the latest twisted and twisted-mqtt.

Thanks, Enoch.

**Comment by astrorafael** [comment]
Hi Enoch,

No, it has never been tested with TLS. Our devices cannot afford it. 

In theory, this is an independent aspect, so it "should work". I would have to do some tests, but unfortunately I have a heavy load of work right now. Anyone volunteers to have a look ai it?

**Comment by aunsbjerg** [comment]
I have twisted-mqtt working with SSL. For my setup, using a connection string like this works:

`
f"ssl:host={hostname}:port={port}:privateKey={private_key}:certKey={cert_key}"
`

**Comment by astrorafael** [comment]
Good to know :-)
I proceed and close the issue
