### ISSUE TITLE
thingsboard experience

### ISSUE THREAD

**Issue by wexi** [astrorafael/twisted-mqtt#14]
Hi, 

Here is an issue I encounter with Thingsboard, the popular (and open-source) IoT dashboard.
I reported it first to Google's group "Thingsboard user discussion and Q&A"  but it actually belongs here.

(1st post)

I am using twisted-mqtt to communicate with Ubuntu installed thingsboard-2.4.2.1 where I am interested in its gateway API.

I defined in TB one "Device A" of the gateway type and successfully connected it via: 
Topic: v1/gateway/connect
Message: {"device":"Device A"}

However, immediately when trying to add a "Device B", which is not predefined in TB, the connection drops.
Topic: v1/gateway/connect
Message: {"device":"Device B"}

Any clue? Should I build Thingsboard from the sources to have a go with a more recent software.

(2nd post)

This must be a mysterious (*) problem with twisted-mqtt since the thingsboard-python-client-sdk behaves as expected (i.e., I can add multiple devices through the gateway).

(*) Mysterious since with the mosquitto servert wisted-mqtt has no issue.

Hints fellows?

Thanks, Enoch.

**Comment by astrorafael** [comment]
IIRC, the connection may be dropped by either two reasons:
1) The server has set up a keepalive timeout that the client is not honoring
2) Two connections using the same MQTT client Id

I'd suggest turning on the logging on the 'mqtt' namespace to see the exchange of PDUs.
