### ISSUE TITLE
Failure: mqtt.error.MQTTWindowError: Request exceeded maximun window size

### ISSUE THREAD

**Issue by Wisit** [astrorafael/twisted-mqtt#4]
I got error message "Failure: mqtt.error.MQTTWindowError: Request exceeded maximun window size" , but my script can running. I would like to know what does it meaning. 

my environment 
centos 6.8
python 2.7 
twsited 16.3.2
twisted-mqtt 0.2.4

![image](https://cloud.githubusercontent.com/assets/1933011/18035139/5d9181ac-6d79-11e6-8998-a6bda6d63b22.png)

**Comment by yombo** [comment]
Did you try the included python example files? Do they work?  You might need to post a GIST to your code.

**Comment by astrorafael** [comment]
"Request exceeded maximun window size" is a concept belonging to PUBLISH packets at QoS = 1 or 2
QoS 1 & 2 PUBLISH packets must be acknowledged from the other side (the broker in this case)
The library can keep a certain limit of packets in a buffer waiting for ACK. 

The window size is = 1 by default but This limit is configurable (up to a certain internal limit). The downside of having a window size > 1 is that selective retransissions of lost packets cannot ensure in-order delivery of packets. If your application is resilent to this (i.e. you timestamp your payloads), then it is a good idea to increase this limit for better performance.

Hope it helps
Rafael
