### ISSUE TITLE
Versions 0.3.5 and 0.3.6 not available via pip

### ISSUE THREAD

**Issue by scibi** [astrorafael/twisted-mqtt#9]
Could you please upload new version?
```
$ pip install 'twisted-mqtt==0.3.6'
Collecting twisted-mqtt==0.3.6
  Could not find a version that satisfies the requirement twisted-mqtt==0.3.6 (from versions: 0.3.2, 0.3.3, 0.3.4)
No matching distribution found for twisted-mqtt==0.3.6
```

**Comment by astrorafael** [comment]
Hi.
At some point during last year the upload mechanism of PiPy changed. Since I was lately using my own software uploaded directly from GitHub this was not an issue for me. But, of course, it is more convenient to have it installed via pop. I'll have a look at it, when I find some spare time.

**Comment by astrorafael** [comment]
Done ! Uoploaded 0.3.6 to PyPi
